# Generated by Django 5.2.6 on 2025-11-27 18:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_by_ong', models.CharField(blank=True, max_length=200)),
                ('bonita_case_id', models.CharField(blank=True, max_length=64, null=True)),
                ('has_monitoring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('WITH_COMMITMENTS', 'Con compromisos'), ('READY', 'Listo para ejecutar'), ('EXECUTING', 'En ejecución'), ('FINISHED', 'Finalizado')], default='OPEN', max_length=20)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observer_label', models.CharField(help_text='Nombre del Consejo o supervisor', max_length=150)),
                ('text', models.TextField(help_text='Descripción de la observación o mejora')),
                ('monitoring_case_id', models.CharField(blank=True, max_length=64, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, verbose_name='Resumen de resultados')),
                ('contributions', models.TextField(blank=True, verbose_name='Aportes recibidos')),
                ('difficulties', models.TextField(blank=True, verbose_name='Dificultades encontradas')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_report', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('request_type', models.CharField(choices=[('ECON', 'Económica'), ('MAT', 'Materiales'), ('MO', 'Mano de obra'), ('OTRO', 'Otro')], max_length=10)),
                ('target_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('reserved_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fulfilled_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Pendiente'), ('RESERVED', 'Reservada'), ('COMPLETED', 'Completada')], db_index=True, default='OPEN', max_length=12)),
                ('needs_help', models.BooleanField(default=True)),
                ('cloud_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='projects.project')),
            ],
            options={
                'db_table': 'collaboration_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project')),
            ],
            options={
                'ordering': ['start_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, db_index=True, max_length=140, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Comprometido'), ('FULFILLED', 'Completado'), ('CANCELLED', 'Cancelado')], db_index=True, default='ACTIVE', max_length=12)),
                ('commitment_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='projects.collaborationrequest')),
            ],
            options={
                'db_table': 'commitment',
                'ordering': ['-commitment_date'],
                'indexes': [models.Index(fields=['request', 'status'], name='commitment_request_591fab_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='collaborationrequest',
            index=models.Index(fields=['project'], name='collaborati_project_e0f4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborationrequest',
            index=models.Index(fields=['status'], name='collaborati_status_d4c635_idx'),
        ),
        migrations.AddConstraint(
            model_name='collaborationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_qty__gte', 0)), name='req_reserved_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='collaborationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('fulfilled_qty__gte', 0)), name='req_fulfilled_nonneg'),
        ),
    ]
