# Generated by Django 5.2.6 on 2025-11-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
    ]
