# Generated by Django 5.2.6 on 2025-10-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='necesidades',
            new_name='needs',
        ),
        migrations.AddField(
            model_name='project',
            name='bonita_case_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
