# Generated by Django 5.2.6 on 2025-11-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_create_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierto'), ('WITH_COMMITMENTS', 'Con compromisos'), ('READY', 'Listo para ejecutar'), ('EXECUTING', 'En ejecución'), ('FINISHED', 'Finalizado')], default='OPEN', max_length=20),
        ),
    ]
