# Generated by Django 5.2.6 on 2025-10-15 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_necesidades_project_needs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='created_by_ong',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ECON', 'Económica'), ('MAT', 'Materiales'), ('MO', 'Mano de obra'), ('OTRO', 'Otro')], max_length=10)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('needs_help', models.BooleanField(default=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs_rel', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200, verbose_name='ONG que colabora')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='projects.need')),
            ],
        ),
        migrations.AddIndex(
            model_name='need',
            index=models.Index(fields=['project'], name='projects_ne_project_4ba9f2_idx'),
        ),
        migrations.AddIndex(
            model_name='need',
            index=models.Index(fields=['needs_help', 'is_fulfilled'], name='projects_ne_needs_h_727336_idx'),
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['need'], name='projects_co_need_id_d374bf_idx'),
        ),
    ]
