# Generated by Django 5.2.6 on 2025-11-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_delete_user_project_created_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='monitoring_case_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
