# Generated by Django 5.2.6 on 2025-11-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_delete_user_project_created_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationrequest',
            name='needs_help',
            field=models.BooleanField(default=True),
        ),
    ]
