# Generated by Django 5.2.6 on 2025-11-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_collaborationrequest_needs_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observation',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
