# Generated by Django 5.2.6 on 2025-11-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_monitoring_case_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
