# Generated by Django 5.2.6 on 2025-10-15 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_notification_project_created_by_ong_need_commitment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='needs',
        ),
    ]
