# Generated by Django 5.2.6 on 2025-11-07 02:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_needs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='need',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='project_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.DeleteModel(
            name='Commitment',
        ),
        migrations.DeleteModel(
            name='Need',
        ),
    ]
