# Generated by Django 5.2.6 on 2025-11-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_observation_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_monitoring',
            field=models.BooleanField(default=False),
        ),
    ]
