# Generated by Django 5.2.6 on 2025-11-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationrequest',
            name='cloud_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
