# Generated by Django 5.2.6 on 2025-11-27 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_collaborationrequest_cloud_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitment',
            name='amount',
        ),
    ]
