# Generated by Django 5.2.6 on 2025-11-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_commitment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Comprometido'), ('FULFILLED', 'Completado'), ('ACCEPTED', 'Aceptado'), ('CANCELLED', 'Cancelado')], db_index=True, default='ACTIVE', max_length=12),
        ),
    ]
