# Generated by Django 5.2.6 on 2025-11-27 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_commitment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, verbose_name='Resumen de resultados')),
                ('contributions', models.TextField(blank=True, verbose_name='Aportes recibidos')),
                ('difficulties', models.TextField(blank=True, verbose_name='Dificultades encontradas')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_report', to='projects.project')),
            ],
        ),
    ]
